# Generated by Django 2.0 on 2018-12-02 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('House', '0001_initial'),
        ('Employment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up_for_trade', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('Employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Employment.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='ShiftType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('number_of_employees', models.IntegerField()),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='House.House')),
            ],
        ),
        migrations.AddField(
            model_name='shift',
            name='Type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scheduling.ShiftType'),
        ),
        migrations.AddField(
            model_name='availability',
            name='ShiftType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scheduling.ShiftType'),
        ),
        migrations.AddField(
            model_name='availability',
            name='days',
            field=models.ManyToManyField(to='Scheduling.Days'),
        ),
        migrations.AddField(
            model_name='availability',
            name='emplyoee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employment.Employee'),
        ),
    ]
