# Generated by Django 2.0 on 2018-12-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scheduling', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='availability',
            old_name='emplyoee',
            new_name='employee',
        ),
        migrations.AlterField(
            model_name='days',
            name='day',
            field=models.CharField(max_length=10),
        ),
    ]
