# Generated by Django 2.0 on 2018-12-25 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('House', '0001_initial'),
        ('Scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleperiod',
            name='House',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='House.House'),
        ),
    ]
