# Generated by Django 2.1.4 on 2019-01-01 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Scheduling', '0002_scheduleperiod_house'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shift',
            old_name='up_for_trade',
            new_name='is_posted',
        ),
    ]
