# Generated by Django 2.0 on 2018-12-16 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employment', '0001_initial'),
        ('Scheduling', '0003_auto_20181210_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='user',
        ),
        migrations.AddField(
            model_name='availability',
            name='employee',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='Employment.Employee'),
        ),
    ]
