# Generated by Django 2.1.4 on 2019-01-02 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Scheduling', '0004_shift_up_for_trade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='Employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='Employment.Employee'),
        ),
    ]
