# Generated by Django 2.0 on 2018-12-16 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Scheduling', '0004_auto_20181216_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Employment.Employee'),
        ),
    ]
