# Generated by Django 2.0 on 2018-12-18 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Scheduling', '0005_auto_20181216_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='Employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employment.Employee'),
        ),
    ]
