# Generated by Django 2.1.4 on 2019-01-02 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Scheduling', '0007_auto_20190102_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='Employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employment.Employee'),
        ),
    ]
