# Generated by Django 2.1.4 on 2019-01-02 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scheduling', '0008_auto_20190102_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='days',
            field=models.ManyToManyField(blank=True, to='Scheduling.Days'),
        ),
    ]
