#!/bin/bash

echo
echo "*************************************************"
echo "This script will dump the current relevant data in the database to fixtures!"
echo "*************************************************"
echo

read -p "Are you sure you want to continue? (yes/no) "
if [ "$REPLY" != "yes" ]; then
  exit 0
fi
echo

echo "Creating fixtures ..."

# Start virtual env
source ~/venv/bin/activate

python manage.py dumpdata --format=json auth.User > config/fixtures/development/Users.json
python manage.py dumpdata --format=json Application > config/fixtures/development/Application.json
python manage.py dumpdata --format=json Employment > config/fixtures/development/Employment.json
python manage.py dumpdata --format=json House > config/fixtures/development/House.json
python manage.py dumpdata --format=json Scheduling > config/fixtures/development/Scheduling.json


# Stop virtual env
deactivate
echo "Done"
