# Generated by Django 2.0 on 2018-12-11 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='Resume',
            field=models.FileField(default='resumes/resume.pdf', upload_to='resumes'),
        ),
    ]
