# Generated by Django 2.0 on 2018-12-20 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0002_applicant_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='Resume',
        ),
    ]
