# Generated by Django 2.0 on 2018-12-21 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0004_applicant_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='old',
            field=models.BooleanField(default=False),
        ),
    ]
