# Generated by Django 2.1.4 on 2019-01-03 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clock',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
