# Generated by Django 2.0 on 2018-12-24 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='max_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='min_hours',
            field=models.IntegerField(default=0),
        ),
    ]
