# Generated by Django 2.0 on 2018-12-20 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employment', '0002_auto_20181220_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clock',
            name='user',
        ),
        migrations.AddField(
            model_name='clock',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Employment.Employee'),
            preserve_default=False,
        ),
    ]
