# Generated by Django 2.1.4 on 2018-12-30 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employment', '0003_employee_num_hours'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clock',
            old_name='day',
            new_name='date',
        ),
    ]
