# Generated by Django 2.1.4 on 2018-12-30 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employment', '0004_auto_20181230_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='clock',
            name='in_out',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
