# Generated by Django 2.1.4 on 2019-01-01 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employment', '0005_clock_in_out'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clock',
            name='date',
        ),
        migrations.AlterField(
            model_name='clock',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
