# Generated by Django 2.1.4 on 2019-01-02 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employment', '0006_auto_20190101_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Employee_Number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pay_rate',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
