# Generated by Django 2.0 on 2018-12-04 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('House', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='Primary_color',
            new_name='primary_color',
        ),
    ]
